sudo: required
dist: trusty
language: node_js
os:
  - linux
node_js:
  - "6"
addons:
  apt:
    packages:
      - google-chrome-stable
before_install:
  - node --version
  - npm --version
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  # Run linting and unit tests
  - npm run cibuild-travis
  # Start development server (needed for E2E tests)
  - npm start&
  # Create distribution bundles
  - npm run build
  # Run E2E tests
  - npm run e2e
