sudo: required
dist: trusty
language: node_js
os:
  - linux
node_js:
  - "6"
addons:
  apt:
    packages:
      - google-chrome-stable
before_install:
  - node --version
  - npm --version
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm run cibuild-travis
  - npm start&
  - npm run build
  - npm run e2e
